// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Caso de prueba 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Caso de prueba 1', async function() {
    // Test name: Caso de prueba 1
    // Step # | name | target | value
    // 1 | open | https://www.nafin.com/portalnf/content/herramientas-de-negocio/simulador-de-creditos/simulador-de-creditos.do | 
    await driver.get("https://www.nafin.com/portalnf/content/herramientas-de-negocio/simulador-de-creditos/simulador-de-creditos.do")
    // 2 | setWindowSize | 1920x1055 | 
    await driver.manage().window().setRect({ width: 1920, height: 1055 })
    // 3 | click | id=dispDate | 
    await driver.findElement(By.id("dispDate")).click()
    // 4 | type | id=dispDate | 12/12/2020
    await driver.findElement(By.id("dispDate")).sendKeys("12/12/2020")
    // 5 | click | css=.row:nth-child(3) | 
    await driver.findElement(By.css(".row:nth-child(3)")).click()
    // 6 | click | id=creditAmount | 
    await driver.findElement(By.id("creditAmount")).click()
    // 7 | click | id=creditAmount | 
    await driver.findElement(By.id("creditAmount")).click()
    // 8 | doubleClick | id=creditAmount | 
    {
      const element = await driver.findElement(By.id("creditAmount"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 9 | type | id=creditAmount | 100000
    await driver.findElement(By.id("creditAmount")).sendKeys("100000")
    // 10 | click | id=paymentMethod | 
    await driver.findElement(By.id("paymentMethod")).click()
    // 11 | select | id=paymentMethod | label=Mensual
    {
      const dropdown = await driver.findElement(By.id("paymentMethod"))
      await dropdown.findElement(By.xpath("//option[. = 'Mensual']")).click()
    }
    // 12 | click | id=period | 
    await driver.findElement(By.id("period")).click()
    // 13 | select | id=period | label=3 años
    {
      const dropdown = await driver.findElement(By.id("period"))
      await dropdown.findElement(By.xpath("//option[. = '3 años']")).click()
    }
    // 14 | click | id=rate | 
    await driver.findElement(By.id("rate")).click()
    // 15 | click | id=rate | 
    await driver.findElement(By.id("rate")).click()
    // 16 | doubleClick | id=rate | 
    {
      const element = await driver.findElement(By.id("rate"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 17 | type | id=rate | 12
    await driver.findElement(By.id("rate")).sendKeys("12")
    // 18 | click | css=.container | 
    await driver.findElement(By.css(".container")).click()
    // 19 | click | css=div:nth-child(7) > .btn | 
    await driver.findElement(By.css("div:nth-child(7) > .btn")).click()
    // 20 | click | css=strong:nth-child(6) | 
    await driver.findElement(By.css("strong:nth-child(6)")).click()
    // 21 | click | css=strong:nth-child(6) | 
    await driver.findElement(By.css("strong:nth-child(6)")).click()
    // 22 | doubleClick | css=strong:nth-child(6) | 
    {
      const element = await driver.findElement(By.css("strong:nth-child(6)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 23 | click | css=tr:nth-child(36) > td:nth-child(7) | 
    await driver.findElement(By.css("tr:nth-child(36) > td:nth-child(7)")).click()
    // 24 | click | css=tr:nth-child(36) > td:nth-child(7) | 
    await driver.findElement(By.css("tr:nth-child(36) > td:nth-child(7)")).click()
    // 25 | assertText | css=tr:nth-child(36) > td:nth-child(7) | $0.00
    // Validar que el saldo final es de 0
    assert(await driver.findElement(By.css("tr:nth-child(36) > td:nth-child(7)")).getText() == "$0.00")
  })
})
